/*
# Seed Non-Verbal Reasoning and English topics and questions

## Overview
The previous migration (20260720130327_add_nvr_and_english_subjects.sql) widened
the `subject` CHECK constraints and added the student level columns for
Non-Verbal Reasoning and English, but never actually inserted any topics or
questions for these two subjects. As a result the subject cards render (they
come from the static SUBJECTS config in the frontend) but the topics list is
empty and practice sessions have nothing to fetch, which reproduces the "no
questions at all" regression.

This migration adds real topic and question rows for Non-Verbal Reasoning and
English, mirroring the structure of the original Maths / Verbal Reasoning seed
(20260713164144_seed_topics_and_questions.sql): 5 topics for NVR, 4 topics for
English, each with 10 questions spanning difficulty 1-10.
*/

-- ============ TOPICS ============
INSERT INTO topics (subject, name, description, order_index) VALUES
('Non-Verbal Reasoning', 'Shape Sequences', 'Spotting the pattern in sequences of shapes and figures.', 11),
('Non-Verbal Reasoning', 'Rotations & Reflections', 'Working out how shapes rotate, flip and reflect.', 12),
('Non-Verbal Reasoning', 'Odd One Out', 'Spotting which shape does not belong with the others.', 13),
('Non-Verbal Reasoning', 'Shape Analogies', 'Completing shape-based analogies (shape A is to B as C is to ?).', 14),
('Non-Verbal Reasoning', 'Nets & 3D Shapes', 'Visualising folded nets and 3D shapes from different angles.', 15),
('English', 'Reading Comprehension', 'Understanding and interpreting short passages.', 16),
('English', 'Grammar & Punctuation', 'Sentence structure, tenses, punctuation and parts of speech.', 17),
('English', 'Vocabulary', 'Synonyms, antonyms and word meanings in context.', 18),
('English', 'Spelling', 'Correct spelling patterns and commonly confused words.', 19)
ON CONFLICT DO NOTHING;

DO $$
DECLARE
  t_shapeseq uuid; t_rot uuid; t_odd uuid; t_analogy uuid; t_nets uuid;
  t_read uuid; t_grammar uuid; t_vocab uuid; t_spell uuid;
BEGIN
  SELECT id INTO t_shapeseq FROM topics WHERE name = 'Shape Sequences';
  SELECT id INTO t_rot FROM topics WHERE name = 'Rotations & Reflections';
  SELECT id INTO t_odd FROM topics WHERE name = 'Odd One Out';
  SELECT id INTO t_analogy FROM topics WHERE name = 'Shape Analogies';
  SELECT id INTO t_nets FROM topics WHERE name = 'Nets & 3D Shapes';
  SELECT id INTO t_read FROM topics WHERE name = 'Reading Comprehension';
  SELECT id INTO t_grammar FROM topics WHERE name = 'Grammar & Punctuation';
  SELECT id INTO t_vocab FROM topics WHERE name = 'Vocabulary';
  SELECT id INTO t_spell FROM topics WHERE name = 'Spelling';

  -- ===== NON-VERBAL REASONING: SHAPE SEQUENCES =====
  INSERT INTO questions (topic_id, subject, difficulty, question_text, question_type, options, correct_answer, hints, explanation) VALUES
  (t_shapeseq, 'Non-Verbal Reasoning', 1, 'Triangle (3 sides), Square (4 sides), Pentagon (5 sides), Hexagon (6 sides), ___?', 'multiple_choice',
   '["Hexagon (6 sides)","Heptagon (7 sides)","Octagon (8 sides)","Circle (0 sides)"]'::jsonb, 'Heptagon (7 sides)',
   '["Count the sides of each shape in order.","The number of sides increases by 1 each time.","6 + 1 = 7 sides, which is a heptagon."]'::jsonb,
   'The sides increase by 1 each time: 3, 4, 5, 6, 7 — a heptagon.'),
  (t_shapeseq, 'Non-Verbal Reasoning', 2, 'A pattern of squares shows 1 dot, 3 dots, 5 dots, 7 dots inside them. How many dots come next?', 'multiple_choice',
   '["8","9","10","11"]'::jsonb, '9',
   '["Look at how much the dot count increases each time.","Each square has 2 more dots than the last.","7 + 2 = 9."]'::jsonb,
   'The dots increase by 2 each time: 1, 3, 5, 7, 9.'),
  (t_shapeseq, 'Non-Verbal Reasoning', 3, 'An arrow points up, then rotates 90° clockwise each step: up, right, down, left, ___?', 'multiple_choice',
   '["up","down","left","right"]'::jsonb, 'up',
   '["Each step turns the arrow a quarter turn clockwise.","After 4 quarter turns the arrow is back where it started.","up → right → down → left → up."]'::jsonb,
   'Four 90° turns make a full 360° turn, back to up.'),
  (t_shapeseq, 'Non-Verbal Reasoning', 4, 'A circle''s shading goes: 1/4 shaded, 2/4 shaded, 3/4 shaded, 4/4 shaded (full), then the pattern resets. What comes right after the fully shaded circle?', 'multiple_choice',
   '["1/4 shaded","2/4 shaded","empty (0/4 shaded)","3/4 shaded"]'::jsonb, 'empty (0/4 shaded)',
   '["The shading grows until it is completely full.","After a full circle, the pattern starts again from nothing.","The next circle is empty, 0/4 shaded."]'::jsonb,
   'After the pattern completes at 4/4, it resets to empty (0/4).'),
  (t_shapeseq, 'Non-Verbal Reasoning', 5, 'A sequence of squares has side lengths 2cm, 4cm, 8cm, 16cm. What is the next side length?', 'multiple_choice',
   '["24cm","28cm","32cm","20cm"]'::jsonb, '32cm',
   '["Compare each side length with the one before it.","Each length is double the previous one.","16 × 2 = 32cm."]'::jsonb,
   'Each side length doubles: 2, 4, 8, 16, 32.'),
  (t_shapeseq, 'Non-Verbal Reasoning', 6, 'A sequence alternates triangle-up and triangle-down, gaining one dot each time: up + 1 dot, down + 2 dots, up + 3 dots, down + 4 dots. What comes next?', 'multiple_choice',
   '["up + 4 dots","up + 5 dots","down + 5 dots","down + 4 dots"]'::jsonb, 'up + 5 dots',
   '["The triangle direction alternates up, down, up, down...","After down it should be up again.","The dot count keeps increasing by 1, so 4 + 1 = 5 dots."]'::jsonb,
   'Direction alternates (next is up) and dots increase by 1 each time (next is 5).'),
  (t_shapeseq, 'Non-Verbal Reasoning', 7, 'A sequence of shapes gains one line of symmetry each time: 1, 2, 3, 4 lines of symmetry. Which regular shape comes next, with 5 lines of symmetry?', 'multiple_choice',
   '["Square (4 lines)","Regular pentagon (5 lines)","Regular hexagon (6 lines)","Rectangle (2 lines)"]'::jsonb, 'Regular pentagon (5 lines)',
   '["A regular polygon with n sides has n lines of symmetry.","You need the shape with exactly 5 lines of symmetry.","A regular pentagon has 5 lines of symmetry."]'::jsonb,
   'A regular pentagon has 5 sides and 5 lines of symmetry.'),
  (t_shapeseq, 'Non-Verbal Reasoning', 8, 'In a 3-row pattern, each row''s shape is rotated 45° more than the row above. Row 1 is at 0°, Row 2 is at 45°. What angle is Row 3 at?', 'multiple_choice',
   '["45°","90°","135°","180°"]'::jsonb, '90°',
   '["Each row adds another 45° of rotation.","Row 2 is 45°, so Row 3 is 45° more than that.","45° + 45° = 90°."]'::jsonb,
   'Row 3 = Row 2 (45°) + 45° = 90°.'),
  (t_shapeseq, 'Non-Verbal Reasoning', 9, 'A sequence of shapes has 1, 1, 2, 3, 5, 8 dots. How many dots does the next shape have?', 'multiple_choice',
   '["11","12","13","10"]'::jsonb, '13',
   '["Each number is the sum of the two numbers before it.","5 + 8 = ?","5 + 8 = 13."]'::jsonb,
   'This is the Fibonacci sequence: 5 + 8 = 13.'),
  (t_shapeseq, 'Non-Verbal Reasoning', 10, 'A shape rotates 30° clockwise and gains one side each step: triangle at 0°, square at 30°, pentagon at 60°, hexagon at 90°. What comes next?', 'multiple_choice',
   '["Heptagon at 120°","Octagon at 120°","Heptagon at 150°","Hexagon at 120°"]'::jsonb, 'Heptagon at 120°',
   '["The number of sides increases by 1 each step: 3, 4, 5, 6, ?","The angle increases by 30° each step: 0°, 30°, 60°, 90°, ?","Next shape has 7 sides (heptagon) at 90° + 30° = 120°."]'::jsonb,
   'Sides: 3,4,5,6,7 (heptagon). Angle: 0,30,60,90,120°.');

  -- ===== NON-VERBAL REASONING: ROTATIONS & REFLECTIONS =====
  INSERT INTO questions (topic_id, subject, difficulty, question_text, question_type, options, correct_answer, hints, explanation) VALUES
  (t_rot, 'Non-Verbal Reasoning', 1, 'A clock hand points to 12. If it rotates 90° clockwise, where does it point?', 'multiple_choice',
   '["3","6","9","12"]'::jsonb, '3',
   '["A full clock face is 360°, split into 12 numbers.","A 90° turn is a quarter of the full circle.","A quarter turn clockwise from 12 lands on 3."]'::jsonb,
   'A 90° clockwise turn from 12 o''clock points to 3.'),
  (t_rot, 'Non-Verbal Reasoning', 2, 'The letter ''b'' is reflected in a vertical mirror line. What letter does it become?', 'multiple_choice',
   '["d","p","q","b"]'::jsonb, 'd',
   '["A vertical mirror flips the letter left-to-right.","Picture the loop of the ''b'' swapping to the other side of the stem.","Flipping ''b'' left-to-right gives ''d''."]'::jsonb,
   'Reflecting ''b'' in a vertical line gives ''d''.'),
  (t_rot, 'Non-Verbal Reasoning', 3, 'A square has a dot in its top-left corner. If the square is rotated 180°, where is the dot now?', 'multiple_choice',
   '["top-left","top-right","bottom-left","bottom-right"]'::jsonb, 'bottom-right',
   '["A 180° rotation turns the shape completely upside down.","The corner directly opposite top-left is the answer.","Top-left rotated 180° lands on bottom-right."]'::jsonb,
   'A 180° rotation swaps each corner with its opposite: top-left becomes bottom-right.'),
  (t_rot, 'Non-Verbal Reasoning', 4, 'What is the result of rotating a shape 180° and then rotating it 180° again?', 'multiple_choice',
   '["A 90° rotation","No change (back to the original position)","A mirror reflection","A 45° rotation"]'::jsonb, 'No change (back to the original position)',
   '["Add the two rotations together.","180° + 180° = 360°.","A 360° rotation is a full turn, back to the start."]'::jsonb,
   '180° + 180° = 360°, a full turn, so the shape looks unchanged.'),
  (t_rot, 'Non-Verbal Reasoning', 5, 'A right-angled triangle has its right angle in the bottom-left corner. After a 90° clockwise rotation, where is the right angle?', 'multiple_choice',
   '["top-left","top-right","bottom-right","bottom-left"]'::jsonb, 'top-left',
   '["Rotating 90° clockwise moves each corner one position clockwise around the square.","Bottom-left moves to the next corner clockwise.","Bottom-left rotated 90° clockwise becomes top-left."]'::jsonb,
   'A 90° clockwise rotation moves bottom-left to top-left.'),
  (t_rot, 'Non-Verbal Reasoning', 6, 'A shape is reflected in a horizontal mirror line, then reflected again in that same line. Compared to the original, the shape is now:', 'multiple_choice',
   '["Rotated 90°","Rotated 180°","Unchanged","Mirror-reversed"]'::jsonb, 'Unchanged',
   '["Reflecting twice in the same mirror line undoes the first reflection.","Think of flipping a card over and then flipping it back.","Two reflections in the same line return the shape to its original position."]'::jsonb,
   'Reflecting twice in the same mirror line cancels out, leaving the shape unchanged.'),
  (t_rot, 'Non-Verbal Reasoning', 7, 'An arrow points north-east (45°). After a 135° clockwise rotation, which direction does it point?', 'multiple_choice',
   '["South","South-west","West","North-west"]'::jsonb, 'South',
   '["Add the rotation to the starting angle.","45° + 135° = 180°.","180° from north, measured clockwise, points south."]'::jsonb,
   '45° + 135° = 180°, which points due south.'),
  (t_rot, 'Non-Verbal Reasoning', 8, 'A shape has 2 lines of symmetry. It is rotated 90°. How many lines of symmetry does the rotated shape have?', 'multiple_choice',
   '["0","1","2","4"]'::jsonb, '2',
   '["Rotating a shape does not change its own symmetry, only its orientation.","The number of lines of symmetry is a property of the shape itself.","The rotated shape still has 2 lines of symmetry."]'::jsonb,
   'Rotation changes orientation, not the number of lines of symmetry — still 2.'),
  (t_rot, 'Non-Verbal Reasoning', 9, 'An arrow points east. It is reflected in a vertical mirror line, then rotated 180°. Which direction does it point now?', 'multiple_choice',
   '["East","West","North","South"]'::jsonb, 'East',
   '["A vertical mirror line swaps east and west.","East reflected in a vertical line becomes west.","Rotating west by 180° brings it back round to east."]'::jsonb,
   'East reflects to west, then a 180° rotation sends west back to east.'),
  (t_rot, 'Non-Verbal Reasoning', 10, 'A square tile has a red triangle in its top-right quarter. The tile is rotated 270° clockwise. Which quarter is the red triangle in now?', 'multiple_choice',
   '["top-left","bottom-left","bottom-right","top-right"]'::jsonb, 'top-left',
   '["270° clockwise is the same as 90° anticlockwise.","Rotating a quarter 90° anticlockwise moves it one position anticlockwise.","Top-right rotated 90° anticlockwise lands in the top-left."]'::jsonb,
   'A 270° clockwise turn equals a 90° anticlockwise turn: top-right moves to top-left.');

  -- ===== NON-VERBAL REASONING: ODD ONE OUT =====
  INSERT INTO questions (topic_id, subject, difficulty, question_text, question_type, options, correct_answer, hints, explanation) VALUES
  (t_odd, 'Non-Verbal Reasoning', 1, 'Which shape does NOT belong: Triangle, Square, Pentagon, Circle?', 'multiple_choice',
   '["Triangle","Square","Pentagon","Circle"]'::jsonb, 'Circle',
   '["Three of these shapes have straight sides and corners.","A circle has no straight sides at all.","Circle is the odd one out."]'::jsonb,
   'Triangle, Square and Pentagon all have straight sides; a Circle has none.'),
  (t_odd, 'Non-Verbal Reasoning', 2, 'Which is the odd one out: Square, Rectangle, Rhombus, Circle?', 'multiple_choice',
   '["Square","Rectangle","Rhombus","Circle"]'::jsonb, 'Circle',
   '["Three of these are four-sided shapes.","A circle has no sides or corners.","Circle is the odd one out."]'::jsonb,
   'Square, Rectangle and Rhombus are all quadrilaterals; a Circle is not.'),
  (t_odd, 'Non-Verbal Reasoning', 3, 'Three shapes have 4 sides. Which does not: Square, Rectangle, Triangle, Trapezium?', 'multiple_choice',
   '["Square","Rectangle","Triangle","Trapezium"]'::jsonb, 'Triangle',
   '["Count the sides of each shape.","A triangle has only 3 sides.","Triangle is the odd one out."]'::jsonb,
   'Square, Rectangle and Trapezium have 4 sides; a Triangle has 3.'),
  (t_odd, 'Non-Verbal Reasoning', 4, 'Which shape has an odd number of sides: Square, Hexagon, Pentagon, Octagon?', 'multiple_choice',
   '["Square","Hexagon","Pentagon","Octagon"]'::jsonb, 'Pentagon',
   '["Count the sides of each shape: 4, 6, 5, 8.","Which of those numbers is odd?","5 (Pentagon) is the only odd number."]'::jsonb,
   'Square (4), Hexagon (6) and Octagon (8) are even; Pentagon (5) is odd.'),
  (t_odd, 'Non-Verbal Reasoning', 5, 'Three of these shapes have all sides equal. Which does not: Equilateral triangle, Square, Regular pentagon, Rectangle?', 'multiple_choice',
   '["Equilateral triangle","Square","Regular pentagon","Rectangle"]'::jsonb, 'Rectangle',
   '["A rectangle usually has two pairs of different side lengths.","The other three shapes are all ''regular'' — every side is the same length.","Rectangle is the odd one out."]'::jsonb,
   'Equilateral triangle, Square and Regular pentagon have all equal sides; a Rectangle does not.'),
  (t_odd, 'Non-Verbal Reasoning', 6, 'Which shape cannot tile a flat surface on its own with no gaps: Square, Equilateral triangle, Regular hexagon, Regular pentagon?', 'multiple_choice',
   '["Square","Equilateral triangle","Regular hexagon","Regular pentagon"]'::jsonb, 'Regular pentagon',
   '["Squares, triangles and hexagons fit together perfectly with no gaps.","Pentagons leave gaps when placed edge to edge.","Regular pentagon is the odd one out."]'::jsonb,
   'Squares, equilateral triangles and regular hexagons tessellate; regular pentagons do not.'),
  (t_odd, 'Non-Verbal Reasoning', 7, 'Three shapes are regular polygons (all sides and angles equal). Which is not: Square, Rhombus, Equilateral triangle, Regular hexagon?', 'multiple_choice',
   '["Square","Rhombus","Equilateral triangle","Regular hexagon"]'::jsonb, 'Rhombus',
   '["A regular polygon needs equal sides AND equal angles.","A rhombus has equal sides, but its angles are not usually all equal.","Rhombus is the odd one out."]'::jsonb,
   'A rhombus has equal sides but unequal angles, so it is not a regular polygon.'),
  (t_odd, 'Non-Verbal Reasoning', 8, 'Which quadrilateral has only one pair of parallel sides: Trapezium, Parallelogram, Rhombus, Rectangle?', 'multiple_choice',
   '["Trapezium","Parallelogram","Rhombus","Rectangle"]'::jsonb, 'Trapezium',
   '["Parallelogram, Rhombus and Rectangle all have two pairs of parallel sides.","A trapezium only has one pair.","Trapezium is the odd one out."]'::jsonb,
   'Parallelogram, Rhombus and Rectangle each have two pairs of parallel sides; a Trapezium has just one.'),
  (t_odd, 'Non-Verbal Reasoning', 9, 'Three shapes have a number of dots that are perfect squares: 4, 9, 16. Which number of dots is NOT a perfect square: 25, 20, 36, 49?', 'multiple_choice',
   '["25","20","36","49"]'::jsonb, '20',
   '["A perfect square is a number you get by multiplying a whole number by itself.","25 = 5×5, 36 = 6×6, 49 = 7×7.","20 is not a perfect square."]'::jsonb,
   '25, 36 and 49 are perfect squares (5², 6², 7²); 20 is not.'),
  (t_odd, 'Non-Verbal Reasoning', 10, 'Three shapes have a number of sides that are prime numbers. Which shape''s side count is NOT prime: Triangle (3), Pentagon (5), Heptagon (7), Hexagon (6)?', 'multiple_choice',
   '["Triangle (3)","Pentagon (5)","Heptagon (7)","Hexagon (6)"]'::jsonb, 'Hexagon (6)',
   '["A prime number has exactly two factors: 1 and itself.","3, 5 and 7 are all prime.","6 is not prime, since 2 × 3 = 6."]'::jsonb,
   '3, 5 and 7 are prime numbers; 6 is not (2 × 3 = 6).');

  -- ===== NON-VERBAL REASONING: SHAPE ANALOGIES =====
  INSERT INTO questions (topic_id, subject, difficulty, question_text, question_type, options, correct_answer, hints, explanation) VALUES
  (t_analogy, 'Non-Verbal Reasoning', 1, 'Triangle is to 3 sides as Square is to ___?', 'multiple_choice',
   '["3 sides","4 sides","5 sides","6 sides"]'::jsonb, '4 sides',
   '["Think about how many sides each shape has.","A triangle has 3 sides.","A square has 4 sides."]'::jsonb,
   'A square has 4 sides, matching the relationship of triangle → 3 sides.'),
  (t_analogy, 'Non-Verbal Reasoning', 2, 'Circle is to round as Square is to ___?', 'multiple_choice',
   '["round","angular","curved","soft"]'::jsonb, 'angular',
   '["A circle has smooth, round edges.","A square has straight edges and sharp corners.","The word for straight-edged and cornered is ''angular''."]'::jsonb,
   'A square has straight, angular edges, unlike a round circle.'),
  (t_analogy, 'Non-Verbal Reasoning', 3, 'Square is to 4 corners as Triangle is to ___?', 'multiple_choice',
   '["2 corners","3 corners","4 corners","5 corners"]'::jsonb, '3 corners',
   '["Count the corners of a square first.","A square has 4 corners.","A triangle has 3 corners."]'::jsonb,
   'A triangle has 3 corners, matching square → 4 corners.'),
  (t_analogy, 'Non-Verbal Reasoning', 4, 'Small square is to big square as small circle is to ___?', 'multiple_choice',
   '["big circle","small triangle","big triangle","medium circle"]'::jsonb, 'big circle',
   '["The relationship is about size, not shape.","The small square becomes a bigger version of the same shape.","A small circle becomes a big circle."]'::jsonb,
   'The pattern is enlarging the same shape, so a small circle becomes a big circle.'),
  (t_analogy, 'Non-Verbal Reasoning', 5, 'A shape turned around a point is to ''rotated'' as a shape flipped in a mirror line is to a ___ shape?', 'multiple_choice',
   '["rotated","reflected","enlarged","shrunk"]'::jsonb, 'reflected',
   '["A turn around a point is called a rotation.","A flip in a mirror line has its own name.","Flipping a shape in a mirror line is called a reflection."]'::jsonb,
   'A shape flipped in a mirror line is described as reflected.'),
  (t_analogy, 'Non-Verbal Reasoning', 6, 'Pentagon is to 5 sides as Octagon is to ___?', 'multiple_choice',
   '["6 sides","7 sides","8 sides","9 sides"]'::jsonb, '8 sides',
   '["Pentagon comes from the Greek for 5.","Octagon comes from the Greek for 8.","An octagon has 8 sides."]'::jsonb,
   'An octagon has 8 sides, matching pentagon → 5 sides.'),
  (t_analogy, 'Non-Verbal Reasoning', 7, 'A cube is to 6 faces as a triangular pyramid (tetrahedron) is to ___ faces?', 'multiple_choice',
   '["3 faces","4 faces","5 faces","6 faces"]'::jsonb, '4 faces',
   '["A cube has 6 square faces.","A tetrahedron has a triangular base plus three triangular sides.","That gives 4 faces in total."]'::jsonb,
   'A tetrahedron has 4 triangular faces in total.'),
  (t_analogy, 'Non-Verbal Reasoning', 8, '2 lines of symmetry is to a rectangle as ___ lines of symmetry is to a regular hexagon?', 'multiple_choice',
   '["4","5","6","8"]'::jsonb, '6',
   '["A regular polygon has as many lines of symmetry as it has sides.","A regular hexagon has 6 sides.","So it has 6 lines of symmetry."]'::jsonb,
   'A regular hexagon has 6 sides and therefore 6 lines of symmetry.'),
  (t_analogy, 'Non-Verbal Reasoning', 9, 'A shape with all sides and angles equal is to ''regular'' as a shape without this property is to ___?', 'multiple_choice',
   '["regular","irregular","symmetrical","congruent"]'::jsonb, 'irregular',
   '["The opposite of ''regular'' in shapes has a specific name.","Think of the prefix that means ''not''.","The word is ''irregular''."]'::jsonb,
   'A shape that is not regular is described as irregular.'),
  (t_analogy, 'Non-Verbal Reasoning', 10, 'A 2D square is to a 3D cube as a 2D circle is to a 3D ___?', 'multiple_choice',
   '["cylinder","sphere","cone","cuboid"]'::jsonb, 'sphere',
   '["A cube is made from squares in three dimensions.","What 3D shape is made from a circle in every direction?","A sphere is the 3D version of a circle."]'::jsonb,
   'A sphere is the 3D equivalent of a 2D circle, just as a cube is the 3D equivalent of a square.');

  -- ===== NON-VERBAL REASONING: NETS & 3D SHAPES =====
  INSERT INTO questions (topic_id, subject, difficulty, question_text, question_type, options, correct_answer, hints, explanation) VALUES
  (t_nets, 'Non-Verbal Reasoning', 1, 'How many faces does a cube have?', 'multiple_choice',
   '["4","5","6","8"]'::jsonb, '6',
   '["Picture a dice, which is cube-shaped.","Count the top, bottom and four sides.","A cube has 6 faces."]'::jsonb,
   'A cube has 6 square faces.'),
  (t_nets, 'Non-Verbal Reasoning', 2, 'How many faces does a triangular prism have?', 'multiple_choice',
   '["4","5","6","7"]'::jsonb, '5',
   '["A triangular prism has 2 triangular ends.","It also has 3 rectangular sides connecting them.","2 + 3 = 5 faces."]'::jsonb,
   'A triangular prism has 2 triangular faces and 3 rectangular faces = 5.'),
  (t_nets, 'Non-Verbal Reasoning', 3, 'A cube''s net is unfolded flat into 2D. How many squares make up the net of a cube?', 'multiple_choice',
   '["4","5","6","8"]'::jsonb, '6',
   '["Each square in the net becomes one face of the cube.","A cube has 6 faces.","So the net has 6 squares."]'::jsonb,
   'A cube net is made of 6 squares, one for each face.'),
  (t_nets, 'Non-Verbal Reasoning', 4, 'How many edges does a cube have?', 'multiple_choice',
   '["8","10","12","6"]'::jsonb, '12',
   '["Each face of a cube is a square with 4 edges, but edges are shared between faces.","Count the edges around the top face (4), the bottom face (4), and the vertical edges connecting them (4).","4 + 4 + 4 = 12."]'::jsonb,
   'A cube has 12 edges: 4 on top, 4 on the bottom, and 4 connecting them.'),
  (t_nets, 'Non-Verbal Reasoning', 5, 'How many vertices (corners) does a cube have?', 'multiple_choice',
   '["6","8","10","12"]'::jsonb, '8',
   '["Count the corners on the top face and the bottom face.","There are 4 corners on top and 4 on the bottom.","4 + 4 = 8 vertices."]'::jsonb,
   'A cube has 8 vertices: 4 on the top face and 4 on the bottom face.'),
  (t_nets, 'Non-Verbal Reasoning', 6, 'A square-based pyramid has how many faces in total, including the base?', 'multiple_choice',
   '["4","5","6","8"]'::jsonb, '5',
   '["Count the base first.","Then count the triangular sides going up to the point.","1 square base + 4 triangular sides = 5 faces."]'::jsonb,
   'A square-based pyramid has 1 square base and 4 triangular faces = 5.'),
  (t_nets, 'Non-Verbal Reasoning', 7, 'Which 3D shape has a net made of one rectangle and two circles?', 'multiple_choice',
   '["cone","cylinder","sphere","cuboid"]'::jsonb, 'cylinder',
   '["The two circles form the flat ends of the shape.","The rectangle wraps around to form the curved side.","This is the net of a cylinder."]'::jsonb,
   'A cylinder unfolds into one rectangle (the curved side) and two circles (the ends).'),
  (t_nets, 'Non-Verbal Reasoning', 8, 'How many faces does a cylinder have, including the top and bottom?', 'multiple_choice',
   '["1","2","3","4"]'::jsonb, '3',
   '["Count the flat circular ends first.","Then count the curved surface as one more face.","2 circular faces + 1 curved face = 3."]'::jsonb,
   'A cylinder has 2 flat circular faces and 1 curved face = 3 in total.'),
  (t_nets, 'Non-Verbal Reasoning', 9, 'A cuboid has all rectangular faces. How many faces does it have in total?', 'multiple_choice',
   '["4","5","6","8"]'::jsonb, '6',
   '["A cuboid is like a stretched cube.","Count the top, bottom and four sides.","A cuboid has 6 faces, just like a cube."]'::jsonb,
   'Like a cube, a cuboid has 6 rectangular faces.'),
  (t_nets, 'Non-Verbal Reasoning', 10, 'If you unfold a triangular pyramid (tetrahedron) into a net, how many triangles make up the net?', 'multiple_choice',
   '["3","4","5","6"]'::jsonb, '4',
   '["A tetrahedron has a triangular base.","It also has three triangular sides meeting at a point.","1 base + 3 sides = 4 triangles."]'::jsonb,
   'A tetrahedron''s net is made of 4 triangles: 1 base and 3 sides.');

  -- ===== ENGLISH: READING COMPREHENSION =====
  INSERT INTO questions (topic_id, subject, difficulty, question_text, question_type, options, correct_answer, hints, explanation) VALUES
  (t_read, 'English', 1, 'Read: "Tom ran to the shop because he needed milk." Why did Tom run to the shop?', 'multiple_choice',
   '["He needed milk","He needed bread","He was late","He wanted to play"]'::jsonb, 'He needed milk',
   '["Look for the word ''because'' — it gives the reason.","The sentence tells you exactly what Tom needed.","Tom ran to the shop because he needed milk."]'::jsonb,
   'The word "because" signals the reason: he needed milk.'),
  (t_read, 'English', 2, 'Read: "The sky turned grey and rain began to fall." What is likely to happen next?', 'multiple_choice',
   '["People might get wet","The sun will get brighter","It will become very hot","Nothing will change"]'::jsonb, 'People might get wet',
   '["Think about what happens when it rains.","Rain falling on people outside has an obvious effect.","People outside are likely to get wet."]'::jsonb,
   'Since it started raining, people outside are likely to get wet.'),
  (t_read, 'English', 3, 'Read: "Although she was tired, Priya finished her homework before dinner." What can we infer about Priya?', 'multiple_choice',
   '["She is lazy","She is determined","She skipped dinner","She has no homework"]'::jsonb, 'She is determined',
   '["The word ''although'' shows a contrast between being tired and still finishing.","Finishing homework despite being tired shows a positive trait.","This suggests she is determined."]'::jsonb,
   'Finishing her homework despite being tired shows Priya is determined.'),
  (t_read, 'English', 4, 'Read: "The old bridge creaked under the weight of the lorry." What does "creaked" suggest about the bridge?', 'multiple_choice',
   '["It was brand new","It made a noise, suggesting it was old or weak","It collapsed","It was painted"]'::jsonb, 'It made a noise, suggesting it was old or weak',
   '["A creaking sound is often associated with old, worn things.","The word ''old'' earlier in the sentence is a clue too.","Creaking suggests the bridge is old or weak, not that it broke."]'::jsonb,
   'Creaking is a sound old or weak structures make under strain.'),
  (t_read, 'English', 5, 'Read: "Despite the heavy traffic, Amir arrived at school on time." What does "despite" show here?', 'multiple_choice',
   '["A reason","A contrast","A result","A question"]'::jsonb, 'A contrast',
   '["Think about what you would expect heavy traffic to cause.","Amir still arrived on time, which is unexpected.","''Despite'' shows a contrast between the traffic and the outcome."]'::jsonb,
   '"Despite" introduces a contrast: heavy traffic, yet he was still on time.'),
  (t_read, 'English', 6, 'Read: "The explorer had faced storms, hunger and fear, yet she pressed on toward the summit." What tone best describes the explorer?', 'multiple_choice',
   '["Fearful and giving up","Determined and persistent","Careless","Bored"]'::jsonb, 'Determined and persistent',
   '["The word ''yet'' shows she kept going despite the hardships.","Pressing on toward a goal despite difficulty shows a clear character trait.","This suggests she is determined and persistent."]'::jsonb,
   '"Yet she pressed on" shows determination despite hardship.'),
  (t_read, 'English', 7, 'Read: "The committee reluctantly agreed to the new policy after much debate." What does "reluctantly" tell us?', 'multiple_choice',
   '["They agreed happily","They agreed unwillingly","They refused","They ignored it"]'::jsonb, 'They agreed unwillingly',
   '["''Reluctantly'' describes how someone feels about doing something.","It suggests hesitation or unwillingness.","The committee agreed, but unwillingly."]'::jsonb,
   '"Reluctantly" means done with hesitation or unwillingness.'),
  (t_read, 'English', 8, 'Read: "Although the novel was long, its vivid characters kept readers engaged until the final page." What is the author''s main point?', 'multiple_choice',
   '["The book was boring","The length didn''t stop the book being enjoyable","The characters were dull","The book had no ending"]'::jsonb, 'The length didn''t stop the book being enjoyable',
   '["''Although'' signals a contrast between the length and the reading experience.","The characters kept readers engaged, despite the length.","So the main point is that length did not reduce enjoyment."]'::jsonb,
   'Despite being long, the vivid characters kept it engaging — length did not hurt enjoyment.'),
  (t_read, 'English', 9, 'Read: "The scientist''s hypothesis, though initially dismissed, was later proven correct by further experiments." What happened to the hypothesis over time?', 'multiple_choice',
   '["It was rejected forever","It went from being rejected to being confirmed","It was never tested","It was proven false"]'::jsonb, 'It went from being rejected to being confirmed',
   '["Look at the two time points: ''initially'' and ''later''.","At first it was dismissed; then it was proven correct.","So it went from rejection to confirmation."]'::jsonb,
   'The hypothesis moved from being dismissed to being proven correct.'),
  (t_read, 'English', 10, 'Read: "What the critics failed to grasp was that the artist''s simplicity was deliberate, not a lack of skill." What is implied about the critics?', 'multiple_choice',
   '["They understood the artist perfectly","They misunderstood the artist''s intention","They praised the artist","They were also artists"]'::jsonb, 'They misunderstood the artist''s intention',
   '["''Failed to grasp'' means they did not understand something.","The critics thought the simplicity meant a lack of skill, which was wrong.","This shows the critics misunderstood the artist''s intention."]'::jsonb,
   '"Failed to grasp" shows the critics misunderstood that the simplicity was intentional.');

  -- ===== ENGLISH: GRAMMAR & PUNCTUATION =====
  INSERT INTO questions (topic_id, subject, difficulty, question_text, question_type, options, correct_answer, hints, explanation) VALUES
  (t_grammar, 'English', 1, 'Which sentence is correctly punctuated?', 'multiple_choice',
   '["I like apples oranges and pears","I like apples, oranges, and pears.","i like apples, oranges, and pears","I like, apples oranges and pears."]'::jsonb, 'I like apples, oranges, and pears.',
   '["A list of items needs commas between them.","The sentence should start with a capital letter and end with a full stop.","Commas separate each item, and the sentence starts with a capital I."]'::jsonb,
   'Items in a list are separated by commas, and the sentence needs correct capitalisation and a full stop.'),
  (t_grammar, 'English', 2, 'Choose the correct verb: "She ___ to school every day."', 'multiple_choice',
   '["walk","walks","walked","walking"]'::jsonb, 'walks',
   '["The subject is ''she'', which is third person singular.","Present tense verbs for ''she'' usually end in -s.","''She walks'' is correct."]'::jsonb,
   'Third person singular present tense takes an -s: "she walks".'),
  (t_grammar, 'English', 3, 'Which word is a noun in this sentence: "The happy dog ran quickly"?', 'multiple_choice',
   '["happy","dog","ran","quickly"]'::jsonb, 'dog',
   '["A noun names a person, place or thing.","''Happy'' describes the dog, and ''ran''/''quickly'' describe the action.","''Dog'' is the thing being described — it''s the noun."]'::jsonb,
   '"Dog" is the noun; "happy" is an adjective and "ran"/"quickly" relate to the verb.'),
  (t_grammar, 'English', 4, 'Which sentence uses the correct past tense?', 'multiple_choice',
   '["Yesterday, she go to the park.","Yesterday, she goes to the park.","Yesterday, she went to the park.","Yesterday, she going to the park."]'::jsonb, 'Yesterday, she went to the park.',
   '["The word ''yesterday'' tells you this happened in the past.","The past tense of ''go'' is irregular.","The correct past tense form is ''went''."]'::jsonb,
   '"Yesterday" signals past tense, and the correct past tense of "go" is "went".'),
  (t_grammar, 'English', 5, 'Which word correctly completes: "Neither the teacher nor the students ___ ready."', 'multiple_choice',
   '["was","were","is","be"]'::jsonb, 'were',
   '["With ''neither...nor'', the verb agrees with the nearer subject.","The nearer subject here is ''students'', which is plural.","Plural subjects take ''were''."]'::jsonb,
   'The verb agrees with the closer subject, "students" (plural), so "were" is correct.'),
  (t_grammar, 'English', 6, 'Choose the sentence with the correct apostrophe use.', 'multiple_choice',
   '["The dogs bone was buried in the garden.","The dog''s bone was buried in the garden.","The dogs'' bone was buried in the garden","The dog,s bone was buried in the garden."]'::jsonb, 'The dog''s bone was buried in the garden.',
   '["An apostrophe + s shows something belongs to one dog.","''Dogs'' without an apostrophe would just mean more than one dog.","''Dog''s'' correctly shows possession by one dog."]'::jsonb,
   'Possession by a single dog is shown with an apostrophe before the s: "dog''s".'),
  (t_grammar, 'English', 7, 'Identify the subordinate clause: "Because it was raining, we stayed inside."', 'multiple_choice',
   '["Because it was raining","we stayed","stayed inside","we stayed inside"]'::jsonb, 'Because it was raining',
   '["A subordinate clause cannot stand alone as a full sentence.","It usually starts with a word like ''because'', ''although'' or ''when''.","''Because it was raining'' depends on the rest of the sentence to make sense."]'::jsonb,
   '"Because it was raining" is the subordinate clause — it cannot stand alone.'),
  (t_grammar, 'English', 8, 'Which sentence correctly uses a semicolon?', 'multiple_choice',
   '["I have a big test tomorrow, I can''t go out tonight.","I have a big test tomorrow; I can''t go out tonight.","I have a big test tomorrow; because I can''t go out tonight.","I have a big test tomorrow: I can''t; go out tonight."]'::jsonb, 'I have a big test tomorrow; I can''t go out tonight.',
   '["A semicolon joins two related, complete sentences.","Both halves of the sentence must be able to stand alone.","''I have a big test tomorrow'' and ''I can''t go out tonight'' can both stand alone, joined correctly by a semicolon."]'::jsonb,
   'A semicolon correctly joins two complete, related sentences.'),
  (t_grammar, 'English', 9, 'Which sentence is in the passive voice?', 'multiple_choice',
   '["The children ate the cake.","The cake was eaten by the children.","The children are eating the cake.","The children will eat the cake."]'::jsonb, 'The cake was eaten by the children.',
   '["In the passive voice, the subject receives the action rather than doing it.","Look for a sentence where the cake is the focus, not the children.","''The cake was eaten by the children'' puts the cake first as the subject."]'::jsonb,
   'Passive voice: the cake (receiver of the action) is the subject of the sentence.'),
  (t_grammar, 'English', 10, 'Which sentence correctly uses "fewer" or "less"?', 'multiple_choice',
   '["There are less apples than oranges.","There are fewer apples than oranges.","There are fewer apple than oranges.","There is fewer apples than oranges."]'::jsonb, 'There are fewer apples than oranges.',
   '["''Fewer'' is used for things you can count, like apples.","''Less'' is used for amounts you cannot count individually.","Since apples can be counted, ''fewer'' is correct."]'::jsonb,
   '"Fewer" is used for countable nouns like apples, not "less".');

  -- ===== ENGLISH: VOCABULARY =====
  INSERT INTO questions (topic_id, subject, difficulty, question_text, question_type, options, correct_answer, hints, explanation) VALUES
  (t_vocab, 'English', 1, 'What does "enormous" mean?', 'multiple_choice',
   '["very small","very big","very fast","very quiet"]'::jsonb, 'very big',
   '["Think of something described as enormous, like an elephant.","It is the opposite of tiny.","Enormous means very big."]'::jsonb,
   '"Enormous" means extremely large.'),
  (t_vocab, 'English', 2, 'Which word means the opposite of "brave"?', 'multiple_choice',
   '["bold","cowardly","strong","fierce"]'::jsonb, 'cowardly',
   '["Brave means having courage.","The opposite would describe someone lacking courage.","Cowardly is the opposite of brave."]'::jsonb,
   '"Cowardly" is the antonym of "brave".'),
  (t_vocab, 'English', 3, 'Choose the synonym for "quick".', 'multiple_choice',
   '["slow","fast","tired","calm"]'::jsonb, 'fast',
   '["A synonym means almost the same thing.","Quick describes speed.","Fast means the same as quick."]'::jsonb,
   '"Fast" is a synonym of "quick".'),
  (t_vocab, 'English', 4, 'What does "ancient" mean?', 'multiple_choice',
   '["very old","very new","very small","very fast"]'::jsonb, 'very old',
   '["Think of ancient ruins or ancient history.","It describes something from long ago.","Ancient means very old."]'::jsonb,
   '"Ancient" describes something extremely old.'),
  (t_vocab, 'English', 5, 'Which word means "to make something better"?', 'multiple_choice',
   '["destroy","improve","ignore","complain"]'::jsonb, 'improve',
   '["Think about what you do to a piece of work to make it better.","It is the opposite of making something worse.","Improve means to make something better."]'::jsonb,
   '"Improve" means to make something better.'),
  (t_vocab, 'English', 6, 'What is the best synonym for "reluctant"?', 'multiple_choice',
   '["eager","unwilling","happy","confident"]'::jsonb, 'unwilling',
   '["Someone reluctant hesitates before doing something.","It is the opposite of being eager.","Unwilling is the closest synonym."]'::jsonb,
   '"Reluctant" means hesitant or unwilling.'),
  (t_vocab, 'English', 7, 'What does "meticulous" mean?', 'multiple_choice',
   '["very careless","very careful and precise","very slow","very loud"]'::jsonb, 'very careful and precise',
   '["Think of someone who checks every detail of their work.","It describes great attention to detail.","Meticulous means very careful and precise."]'::jsonb,
   '"Meticulous" describes showing great attention to detail.'),
  (t_vocab, 'English', 8, 'Which word means the opposite of "transparent"?', 'multiple_choice',
   '["clear","see-through","opaque","glassy"]'::jsonb, 'opaque',
   '["Transparent means you can see through it.","The opposite means light cannot pass through.","Opaque is the opposite of transparent."]'::jsonb,
   '"Opaque" means not able to be seen through, the opposite of "transparent".'),
  (t_vocab, 'English', 9, 'What does "ambiguous" mean?', 'multiple_choice',
   '["very clear","open to more than one interpretation","completely wrong","extremely simple"]'::jsonb, 'open to more than one interpretation',
   '["Think of a sentence that could be understood in different ways.","It is the opposite of being perfectly clear.","Ambiguous means open to more than one meaning."]'::jsonb,
   '"Ambiguous" describes something that can be understood in more than one way.'),
  (t_vocab, 'English', 10, 'Choose the best synonym for "benevolent".', 'multiple_choice',
   '["cruel and mean","kind and generous","angry and loud","shy and quiet"]'::jsonb, 'kind and generous',
   '["Think of a benevolent king who helps his people.","It describes a caring, generous nature.","Benevolent means kind and generous."]'::jsonb,
   '"Benevolent" means kind and generous.');

  -- ===== ENGLISH: SPELLING =====
  INSERT INTO questions (topic_id, subject, difficulty, question_text, question_type, options, correct_answer, hints, explanation) VALUES
  (t_spell, 'English', 1, 'Which is the correct spelling?', 'multiple_choice',
   '["freind","friend","frend","friand"]'::jsonb, 'friend',
   '["Remember the rule: i before e except after c.","Sound it out: fri-end.","''Friend'' is spelled f-r-i-e-n-d."]'::jsonb,
   '"Friend" follows the i-before-e pattern: f-r-i-e-n-d.'),
  (t_spell, 'English', 2, 'Which is the correct spelling?', 'multiple_choice',
   '["becuase","because","becaus","becouse"]'::jsonb, 'because',
   '["Break it into parts: be-cause.","It ends in ''-ause'', not ''-ouse'' or ''-aus''.","''Because'' is spelled b-e-c-a-u-s-e."]'::jsonb,
   '"Because" is spelled b-e-c-a-u-s-e.'),
  (t_spell, 'English', 3, 'Which is the correct spelling?', 'multiple_choice',
   '["neccessary","necesary","necessary","neccesary"]'::jsonb, 'necessary',
   '["Remember: one collar, two sleeves — one ''c'', two ''s''.","It has a single ''c'' followed by double ''s''.","''Necessary'' is spelled n-e-c-e-s-s-a-r-y."]'::jsonb,
   '"Necessary" has one "c" and two "s"s.'),
  (t_spell, 'English', 4, 'Which is the correct spelling?', 'multiple_choice',
   '["seperate","separate","seperete","separete"]'::jsonb, 'separate',
   '["Remember: there''s ''a rat'' in sep-a-rate.","The middle vowel is ''a'', not ''e''.","''Separate'' is spelled s-e-p-a-r-a-t-e."]'::jsonb,
   '"Separate" contains "a rat" in the middle: sep-a-rate.'),
  (t_spell, 'English', 5, 'Which is the correct spelling?', 'multiple_choice',
   '["definately","definitly","definitely","deffinitely"]'::jsonb, 'definitely',
   '["The word contains ''finite'' in the middle.","It is not spelled with ''a'' in the middle.","''Definitely'' is spelled d-e-f-i-n-i-t-e-l-y."]'::jsonb,
   '"Definitely" contains "finite": defi-nite-ly.'),
  (t_spell, 'English', 6, 'Which is the correct spelling?', 'multiple_choice',
   '["accomodate","acommodate","accommodate","acomodate"]'::jsonb, 'accommodate',
   '["Remember: two ''c''s and two ''m''s.","It has double letters in two places.","''Accommodate'' is spelled a-c-c-o-m-m-o-d-a-t-e."]'::jsonb,
   '"Accommodate" has double "c" and double "m".'),
  (t_spell, 'English', 7, 'Which word is spelled correctly?', 'multiple_choice',
   '["concience","conscious","conscience","consciense"]'::jsonb, 'conscience',
   '["This word means your inner sense of right and wrong.","It is different from ''conscious'', which means being awake and aware.","''Conscience'' is spelled c-o-n-s-c-i-e-n-c-e."]'::jsonb,
   '"Conscience" (right/wrong) is spelled differently from "conscious" (aware).'),
  (t_spell, 'English', 8, 'Which word is spelled correctly?', 'multiple_choice',
   '["embaras","embarass","embarrass","embarras"]'::jsonb, 'embarrass',
   '["Remember: two ''r''s and two ''s''s.","It has double letters in two places.","''Embarrass'' is spelled e-m-b-a-r-r-a-s-s."]'::jsonb,
   '"Embarrass" has double "r" and double "s".'),
  (t_spell, 'English', 9, 'Which word is spelled correctly?', 'multiple_choice',
   '["occurence","occurrance","occurrence","ocurrence"]'::jsonb, 'occurrence',
   '["Remember: double ''c'', double ''r''.","It ends in ''-ence'', not ''-ance''.","''Occurrence'' is spelled o-c-c-u-r-r-e-n-c-e."]'::jsonb,
   '"Occurrence" has double "c", double "r", and ends in "-ence".'),
  (t_spell, 'English', 10, 'Which word is spelled correctly?', 'multiple_choice',
   '["rythm","rhythm","rhytm","rythem"]'::jsonb, 'rhythm',
   '["This tricky word has no vowels except ''y''.","It starts with ''rh'', not ''r''.","''Rhythm'' is spelled r-h-y-t-h-m."]'::jsonb,
   '"Rhythm" is spelled r-h-y-t-h-m, with no standard vowels.');

END $$;
